/* 
 * Get into Teaching API - V1
 *
 *   Provides a RESTful API for integrating with the Get into Teaching CRM.    The Get into Teaching (GIT) API sits in front of the GIT CRM, which uses the [Microsoft Dynamics365](https://docs.microsoft.com/en-us/dynamics365/) platform (the [Customer Engagement](https://docs.microsoft.com/en-us/dynamics365/customerengagement/on-premises/developer/overview) module is used for storing Candidate information and the [Marketing](https://docs.microsoft.com/en-us/dynamics365/marketing/developer/using-events-api) module for managing Events).    The GIT API aims to provide:    * Simple, task-based RESTful APIs.  * Message queueing (while the GIT CRM is offline for updates).  * Validation to ensure consistency across services writing to the GIT CRM.                          
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = GetIntoTeachingApi.Client.Client.SwaggerDateConverter;

namespace GetIntoTeachingApi.Client.Model
{
    /// <summary>
    /// CandidatePrivacyPolicy
    /// </summary>
    [DataContract]
    public partial class CandidatePrivacyPolicy :  IEquatable<CandidatePrivacyPolicy>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CandidatePrivacyPolicy" /> class.
        /// </summary>
        /// <param name="acceptedPolicyId">acceptedPolicyId.</param>
        /// <param name="id">id.</param>
        public CandidatePrivacyPolicy(Guid? acceptedPolicyId = default(Guid?), Guid? id = default(Guid?))
        {
            this.AcceptedPolicyId = acceptedPolicyId;
            this.Id = id;
        }
        
        /// <summary>
        /// Gets or Sets AcceptedPolicyId
        /// </summary>
        [DataMember(Name="acceptedPolicyId", EmitDefaultValue=false)]
        public Guid? AcceptedPolicyId { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public Guid? Id { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CandidatePrivacyPolicy {\n");
            sb.Append("  AcceptedPolicyId: ").Append(AcceptedPolicyId).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CandidatePrivacyPolicy);
        }

        /// <summary>
        /// Returns true if CandidatePrivacyPolicy instances are equal
        /// </summary>
        /// <param name="input">Instance of CandidatePrivacyPolicy to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CandidatePrivacyPolicy input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.AcceptedPolicyId == input.AcceptedPolicyId ||
                    (this.AcceptedPolicyId != null &&
                    this.AcceptedPolicyId.Equals(input.AcceptedPolicyId))
                ) && 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.AcceptedPolicyId != null)
                    hashCode = hashCode * 59 + this.AcceptedPolicyId.GetHashCode();
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
