/* 
 * Get into Teaching API - V1
 *
 *   Provides a RESTful API for integrating with the Get into Teaching CRM.    The Get into Teaching (GIT) API sits in front of the GIT CRM, which uses the [Microsoft Dynamics365](https://docs.microsoft.com/en-us/dynamics365/) platform (the [Customer Engagement](https://docs.microsoft.com/en-us/dynamics365/customerengagement/on-premises/developer/overview) module is used for storing Candidate information and the [Marketing](https://docs.microsoft.com/en-us/dynamics365/marketing/developer/using-events-api) module for managing Events).    The GIT API aims to provide:    * Simple, task-based RESTful APIs.  * Message queueing (while the GIT CRM is offline for updates).  * Validation to ensure consistency across services writing to the GIT CRM.                          
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = GetIntoTeachingApi.Client.Client.SwaggerDateConverter;

namespace GetIntoTeachingApi.Client.Model
{
    /// <summary>
    /// CandidatePastTeachingPosition
    /// </summary>
    [DataContract]
    public partial class CandidatePastTeachingPosition :  IEquatable<CandidatePastTeachingPosition>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CandidatePastTeachingPosition" /> class.
        /// </summary>
        /// <param name="subjectTaughtId">subjectTaughtId.</param>
        /// <param name="educationPhaseId">educationPhaseId.</param>
        /// <param name="id">id.</param>
        public CandidatePastTeachingPosition(Guid? subjectTaughtId = default(Guid?), int? educationPhaseId = default(int?), Guid? id = default(Guid?))
        {
            this.SubjectTaughtId = subjectTaughtId;
            this.EducationPhaseId = educationPhaseId;
            this.Id = id;
        }
        
        /// <summary>
        /// Gets or Sets SubjectTaughtId
        /// </summary>
        [DataMember(Name="subjectTaughtId", EmitDefaultValue=false)]
        public Guid? SubjectTaughtId { get; set; }

        /// <summary>
        /// Gets or Sets EducationPhaseId
        /// </summary>
        [DataMember(Name="educationPhaseId", EmitDefaultValue=false)]
        public int? EducationPhaseId { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public Guid? Id { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CandidatePastTeachingPosition {\n");
            sb.Append("  SubjectTaughtId: ").Append(SubjectTaughtId).Append("\n");
            sb.Append("  EducationPhaseId: ").Append(EducationPhaseId).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CandidatePastTeachingPosition);
        }

        /// <summary>
        /// Returns true if CandidatePastTeachingPosition instances are equal
        /// </summary>
        /// <param name="input">Instance of CandidatePastTeachingPosition to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CandidatePastTeachingPosition input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.SubjectTaughtId == input.SubjectTaughtId ||
                    (this.SubjectTaughtId != null &&
                    this.SubjectTaughtId.Equals(input.SubjectTaughtId))
                ) && 
                (
                    this.EducationPhaseId == input.EducationPhaseId ||
                    (this.EducationPhaseId != null &&
                    this.EducationPhaseId.Equals(input.EducationPhaseId))
                ) && 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.SubjectTaughtId != null)
                    hashCode = hashCode * 59 + this.SubjectTaughtId.GetHashCode();
                if (this.EducationPhaseId != null)
                    hashCode = hashCode * 59 + this.EducationPhaseId.GetHashCode();
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
