/* 
 * Get into Teaching API - V1
 *
 *   Provides a RESTful API for integrating with the Get into Teaching CRM.    The Get into Teaching (GIT) API sits in front of the GIT CRM, which uses the [Microsoft Dynamics365](https://docs.microsoft.com/en-us/dynamics365/) platform (the [Customer Engagement](https://docs.microsoft.com/en-us/dynamics365/customerengagement/on-premises/developer/overview) module is used for storing Candidate information and the [Marketing](https://docs.microsoft.com/en-us/dynamics365/marketing/developer/using-events-api) module for managing Events).    The GIT API aims to provide:    * Simple, task-based RESTful APIs.  * Message queueing (while the GIT CRM is offline for updates).  * Validation to ensure consistency across services writing to the GIT CRM.                          
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using GetIntoTeachingApi.Client.Client;
using GetIntoTeachingApi.Client.Model;

namespace GetIntoTeachingApi.Client.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ITeachingEventsApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Adds an attendee to a teaching event.
        /// </summary>
        /// <remarks>
        /// If the &#x60;CandidateId&#x60; is specified then the existing candidate will be registered for the event, otherwise a new candidate will be created.
        /// </remarks>
        /// <exception cref="GetIntoTeachingApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The &#x60;id&#x60; of the &#x60;TeachingEvent&#x60;.</param>
        /// <param name="body">Attendee to add to the teaching event.</param>
        /// <returns></returns>
        void AddTeachingEventAttendee (Guid? id, TeachingEventRegistrationRequest body);

        /// <summary>
        /// Adds an attendee to a teaching event.
        /// </summary>
        /// <remarks>
        /// If the &#x60;CandidateId&#x60; is specified then the existing candidate will be registered for the event, otherwise a new candidate will be created.
        /// </remarks>
        /// <exception cref="GetIntoTeachingApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The &#x60;id&#x60; of the &#x60;TeachingEvent&#x60;.</param>
        /// <param name="body">Attendee to add to the teaching event.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> AddTeachingEventAttendeeWithHttpInfo (Guid? id, TeachingEventRegistrationRequest body);
        /// <summary>
        /// Retrieves an event.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="GetIntoTeachingApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The &#x60;id&#x60; of the &#x60;TeachingEvent&#x60;.</param>
        /// <returns>TeachingEvent</returns>
        TeachingEvent GetTeachingEvent (Guid? id);

        /// <summary>
        /// Retrieves an event.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="GetIntoTeachingApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The &#x60;id&#x60; of the &#x60;TeachingEvent&#x60;.</param>
        /// <returns>ApiResponse of TeachingEvent</returns>
        ApiResponse<TeachingEvent> GetTeachingEventWithHttpInfo (Guid? id);
        /// <summary>
        /// Retrieves the upcoming teaching events.
        /// </summary>
        /// <remarks>
        ///   Retrieves the upcoming teaching events; limited to 10 by default, but this can be increased to a   maximum of 50 using the &#x60;limit&#x60; query parameter.
        /// </remarks>
        /// <exception cref="GetIntoTeachingApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit">Number of results to return (maximum of 50). (optional, default to 10)</param>
        /// <returns>List&lt;TeachingEvent&gt;</returns>
        List<TeachingEvent> GetUpcomingTeachingEvents (int? limit = null);

        /// <summary>
        /// Retrieves the upcoming teaching events.
        /// </summary>
        /// <remarks>
        ///   Retrieves the upcoming teaching events; limited to 10 by default, but this can be increased to a   maximum of 50 using the &#x60;limit&#x60; query parameter.
        /// </remarks>
        /// <exception cref="GetIntoTeachingApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit">Number of results to return (maximum of 50). (optional, default to 10)</param>
        /// <returns>ApiResponse of List&lt;TeachingEvent&gt;</returns>
        ApiResponse<List<TeachingEvent>> GetUpcomingTeachingEventsWithHttpInfo (int? limit = null);
        /// <summary>
        /// Searches for teaching events.
        /// </summary>
        /// <remarks>
        /// Searches for teaching events by postcode. Optionally limit the results by distance (in miles) and the type of event.
        /// </remarks>
        /// <exception cref="GetIntoTeachingApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="postcode"></param>
        /// <param name="radius"> (optional)</param>
        /// <param name="typeId"> (optional)</param>
        /// <param name="startAfter"> (optional)</param>
        /// <param name="startBefore"> (optional)</param>
        /// <param name="radiusInKm"> (optional)</param>
        /// <returns>List&lt;TeachingEvent&gt;</returns>
        List<TeachingEvent> SearchTeachingEvents (string postcode, int? radius = null, int? typeId = null, DateTime? startAfter = null, DateTime? startBefore = null, double? radiusInKm = null);

        /// <summary>
        /// Searches for teaching events.
        /// </summary>
        /// <remarks>
        /// Searches for teaching events by postcode. Optionally limit the results by distance (in miles) and the type of event.
        /// </remarks>
        /// <exception cref="GetIntoTeachingApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="postcode"></param>
        /// <param name="radius"> (optional)</param>
        /// <param name="typeId"> (optional)</param>
        /// <param name="startAfter"> (optional)</param>
        /// <param name="startBefore"> (optional)</param>
        /// <param name="radiusInKm"> (optional)</param>
        /// <returns>ApiResponse of List&lt;TeachingEvent&gt;</returns>
        ApiResponse<List<TeachingEvent>> SearchTeachingEventsWithHttpInfo (string postcode, int? radius = null, int? typeId = null, DateTime? startAfter = null, DateTime? startBefore = null, double? radiusInKm = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Adds an attendee to a teaching event.
        /// </summary>
        /// <remarks>
        /// If the &#x60;CandidateId&#x60; is specified then the existing candidate will be registered for the event, otherwise a new candidate will be created.
        /// </remarks>
        /// <exception cref="GetIntoTeachingApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The &#x60;id&#x60; of the &#x60;TeachingEvent&#x60;.</param>
        /// <param name="body">Attendee to add to the teaching event.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task AddTeachingEventAttendeeAsync (Guid? id, TeachingEventRegistrationRequest body);

        /// <summary>
        /// Adds an attendee to a teaching event.
        /// </summary>
        /// <remarks>
        /// If the &#x60;CandidateId&#x60; is specified then the existing candidate will be registered for the event, otherwise a new candidate will be created.
        /// </remarks>
        /// <exception cref="GetIntoTeachingApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The &#x60;id&#x60; of the &#x60;TeachingEvent&#x60;.</param>
        /// <param name="body">Attendee to add to the teaching event.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> AddTeachingEventAttendeeAsyncWithHttpInfo (Guid? id, TeachingEventRegistrationRequest body);
        /// <summary>
        /// Retrieves an event.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="GetIntoTeachingApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The &#x60;id&#x60; of the &#x60;TeachingEvent&#x60;.</param>
        /// <returns>Task of TeachingEvent</returns>
        System.Threading.Tasks.Task<TeachingEvent> GetTeachingEventAsync (Guid? id);

        /// <summary>
        /// Retrieves an event.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="GetIntoTeachingApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The &#x60;id&#x60; of the &#x60;TeachingEvent&#x60;.</param>
        /// <returns>Task of ApiResponse (TeachingEvent)</returns>
        System.Threading.Tasks.Task<ApiResponse<TeachingEvent>> GetTeachingEventAsyncWithHttpInfo (Guid? id);
        /// <summary>
        /// Retrieves the upcoming teaching events.
        /// </summary>
        /// <remarks>
        ///   Retrieves the upcoming teaching events; limited to 10 by default, but this can be increased to a   maximum of 50 using the &#x60;limit&#x60; query parameter.
        /// </remarks>
        /// <exception cref="GetIntoTeachingApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit">Number of results to return (maximum of 50). (optional, default to 10)</param>
        /// <returns>Task of List&lt;TeachingEvent&gt;</returns>
        System.Threading.Tasks.Task<List<TeachingEvent>> GetUpcomingTeachingEventsAsync (int? limit = null);

        /// <summary>
        /// Retrieves the upcoming teaching events.
        /// </summary>
        /// <remarks>
        ///   Retrieves the upcoming teaching events; limited to 10 by default, but this can be increased to a   maximum of 50 using the &#x60;limit&#x60; query parameter.
        /// </remarks>
        /// <exception cref="GetIntoTeachingApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit">Number of results to return (maximum of 50). (optional, default to 10)</param>
        /// <returns>Task of ApiResponse (List&lt;TeachingEvent&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<TeachingEvent>>> GetUpcomingTeachingEventsAsyncWithHttpInfo (int? limit = null);
        /// <summary>
        /// Searches for teaching events.
        /// </summary>
        /// <remarks>
        /// Searches for teaching events by postcode. Optionally limit the results by distance (in miles) and the type of event.
        /// </remarks>
        /// <exception cref="GetIntoTeachingApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="postcode"></param>
        /// <param name="radius"> (optional)</param>
        /// <param name="typeId"> (optional)</param>
        /// <param name="startAfter"> (optional)</param>
        /// <param name="startBefore"> (optional)</param>
        /// <param name="radiusInKm"> (optional)</param>
        /// <returns>Task of List&lt;TeachingEvent&gt;</returns>
        System.Threading.Tasks.Task<List<TeachingEvent>> SearchTeachingEventsAsync (string postcode, int? radius = null, int? typeId = null, DateTime? startAfter = null, DateTime? startBefore = null, double? radiusInKm = null);

        /// <summary>
        /// Searches for teaching events.
        /// </summary>
        /// <remarks>
        /// Searches for teaching events by postcode. Optionally limit the results by distance (in miles) and the type of event.
        /// </remarks>
        /// <exception cref="GetIntoTeachingApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="postcode"></param>
        /// <param name="radius"> (optional)</param>
        /// <param name="typeId"> (optional)</param>
        /// <param name="startAfter"> (optional)</param>
        /// <param name="startBefore"> (optional)</param>
        /// <param name="radiusInKm"> (optional)</param>
        /// <returns>Task of ApiResponse (List&lt;TeachingEvent&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<TeachingEvent>>> SearchTeachingEventsAsyncWithHttpInfo (string postcode, int? radius = null, int? typeId = null, DateTime? startAfter = null, DateTime? startBefore = null, double? radiusInKm = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class TeachingEventsApi : ITeachingEventsApi
    {
        private GetIntoTeachingApi.Client.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="TeachingEventsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public TeachingEventsApi(String basePath)
        {
            this.Configuration = new GetIntoTeachingApi.Client.Client.Configuration { BasePath = basePath };

            ExceptionFactory = GetIntoTeachingApi.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TeachingEventsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public TeachingEventsApi(GetIntoTeachingApi.Client.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = GetIntoTeachingApi.Client.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = GetIntoTeachingApi.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public GetIntoTeachingApi.Client.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public GetIntoTeachingApi.Client.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Adds an attendee to a teaching event. If the &#x60;CandidateId&#x60; is specified then the existing candidate will be registered for the event, otherwise a new candidate will be created.
        /// </summary>
        /// <exception cref="GetIntoTeachingApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The &#x60;id&#x60; of the &#x60;TeachingEvent&#x60;.</param>
        /// <param name="body">Attendee to add to the teaching event.</param>
        /// <returns></returns>
        public void AddTeachingEventAttendee (Guid? id, TeachingEventRegistrationRequest body)
        {
             AddTeachingEventAttendeeWithHttpInfo(id, body);
        }

        /// <summary>
        /// Adds an attendee to a teaching event. If the &#x60;CandidateId&#x60; is specified then the existing candidate will be registered for the event, otherwise a new candidate will be created.
        /// </summary>
        /// <exception cref="GetIntoTeachingApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The &#x60;id&#x60; of the &#x60;TeachingEvent&#x60;.</param>
        /// <param name="body">Attendee to add to the teaching event.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public ApiResponse<Object> AddTeachingEventAttendeeWithHttpInfo (Guid? id, TeachingEventRegistrationRequest body)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling TeachingEventsApi->AddTeachingEventAttendee");
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling TeachingEventsApi->AddTeachingEventAttendee");

            var localVarPath = "/api/teaching_events/{id}/attendees";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/_*+json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // authentication (apiKey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("AddTeachingEventAttendee", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

        /// <summary>
        /// Adds an attendee to a teaching event. If the &#x60;CandidateId&#x60; is specified then the existing candidate will be registered for the event, otherwise a new candidate will be created.
        /// </summary>
        /// <exception cref="GetIntoTeachingApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The &#x60;id&#x60; of the &#x60;TeachingEvent&#x60;.</param>
        /// <param name="body">Attendee to add to the teaching event.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task AddTeachingEventAttendeeAsync (Guid? id, TeachingEventRegistrationRequest body)
        {
             await AddTeachingEventAttendeeAsyncWithHttpInfo(id, body);

        }

        /// <summary>
        /// Adds an attendee to a teaching event. If the &#x60;CandidateId&#x60; is specified then the existing candidate will be registered for the event, otherwise a new candidate will be created.
        /// </summary>
        /// <exception cref="GetIntoTeachingApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The &#x60;id&#x60; of the &#x60;TeachingEvent&#x60;.</param>
        /// <param name="body">Attendee to add to the teaching event.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> AddTeachingEventAttendeeAsyncWithHttpInfo (Guid? id, TeachingEventRegistrationRequest body)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling TeachingEventsApi->AddTeachingEventAttendee");
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling TeachingEventsApi->AddTeachingEventAttendee");

            var localVarPath = "/api/teaching_events/{id}/attendees";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/_*+json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // authentication (apiKey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("AddTeachingEventAttendee", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

        /// <summary>
        /// Retrieves an event. 
        /// </summary>
        /// <exception cref="GetIntoTeachingApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The &#x60;id&#x60; of the &#x60;TeachingEvent&#x60;.</param>
        /// <returns>TeachingEvent</returns>
        public TeachingEvent GetTeachingEvent (Guid? id)
        {
             ApiResponse<TeachingEvent> localVarResponse = GetTeachingEventWithHttpInfo(id);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Retrieves an event. 
        /// </summary>
        /// <exception cref="GetIntoTeachingApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The &#x60;id&#x60; of the &#x60;TeachingEvent&#x60;.</param>
        /// <returns>ApiResponse of TeachingEvent</returns>
        public ApiResponse< TeachingEvent > GetTeachingEventWithHttpInfo (Guid? id)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling TeachingEventsApi->GetTeachingEvent");

            var localVarPath = "/api/teaching_events/{id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter

            // authentication (apiKey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetTeachingEvent", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<TeachingEvent>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (TeachingEvent) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(TeachingEvent)));
        }

        /// <summary>
        /// Retrieves an event. 
        /// </summary>
        /// <exception cref="GetIntoTeachingApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The &#x60;id&#x60; of the &#x60;TeachingEvent&#x60;.</param>
        /// <returns>Task of TeachingEvent</returns>
        public async System.Threading.Tasks.Task<TeachingEvent> GetTeachingEventAsync (Guid? id)
        {
             ApiResponse<TeachingEvent> localVarResponse = await GetTeachingEventAsyncWithHttpInfo(id);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Retrieves an event. 
        /// </summary>
        /// <exception cref="GetIntoTeachingApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The &#x60;id&#x60; of the &#x60;TeachingEvent&#x60;.</param>
        /// <returns>Task of ApiResponse (TeachingEvent)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<TeachingEvent>> GetTeachingEventAsyncWithHttpInfo (Guid? id)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling TeachingEventsApi->GetTeachingEvent");

            var localVarPath = "/api/teaching_events/{id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter

            // authentication (apiKey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetTeachingEvent", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<TeachingEvent>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (TeachingEvent) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(TeachingEvent)));
        }

        /// <summary>
        /// Retrieves the upcoming teaching events.   Retrieves the upcoming teaching events; limited to 10 by default, but this can be increased to a   maximum of 50 using the &#x60;limit&#x60; query parameter.
        /// </summary>
        /// <exception cref="GetIntoTeachingApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit">Number of results to return (maximum of 50). (optional, default to 10)</param>
        /// <returns>List&lt;TeachingEvent&gt;</returns>
        public List<TeachingEvent> GetUpcomingTeachingEvents (int? limit = null)
        {
             ApiResponse<List<TeachingEvent>> localVarResponse = GetUpcomingTeachingEventsWithHttpInfo(limit);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Retrieves the upcoming teaching events.   Retrieves the upcoming teaching events; limited to 10 by default, but this can be increased to a   maximum of 50 using the &#x60;limit&#x60; query parameter.
        /// </summary>
        /// <exception cref="GetIntoTeachingApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit">Number of results to return (maximum of 50). (optional, default to 10)</param>
        /// <returns>ApiResponse of List&lt;TeachingEvent&gt;</returns>
        public ApiResponse< List<TeachingEvent> > GetUpcomingTeachingEventsWithHttpInfo (int? limit = null)
        {

            var localVarPath = "/api/teaching_events/upcoming";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (limit != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "limit", limit)); // query parameter

            // authentication (apiKey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetUpcomingTeachingEvents", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<TeachingEvent>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (List<TeachingEvent>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<TeachingEvent>)));
        }

        /// <summary>
        /// Retrieves the upcoming teaching events.   Retrieves the upcoming teaching events; limited to 10 by default, but this can be increased to a   maximum of 50 using the &#x60;limit&#x60; query parameter.
        /// </summary>
        /// <exception cref="GetIntoTeachingApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit">Number of results to return (maximum of 50). (optional, default to 10)</param>
        /// <returns>Task of List&lt;TeachingEvent&gt;</returns>
        public async System.Threading.Tasks.Task<List<TeachingEvent>> GetUpcomingTeachingEventsAsync (int? limit = null)
        {
             ApiResponse<List<TeachingEvent>> localVarResponse = await GetUpcomingTeachingEventsAsyncWithHttpInfo(limit);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Retrieves the upcoming teaching events.   Retrieves the upcoming teaching events; limited to 10 by default, but this can be increased to a   maximum of 50 using the &#x60;limit&#x60; query parameter.
        /// </summary>
        /// <exception cref="GetIntoTeachingApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit">Number of results to return (maximum of 50). (optional, default to 10)</param>
        /// <returns>Task of ApiResponse (List&lt;TeachingEvent&gt;)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<List<TeachingEvent>>> GetUpcomingTeachingEventsAsyncWithHttpInfo (int? limit = null)
        {

            var localVarPath = "/api/teaching_events/upcoming";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (limit != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "limit", limit)); // query parameter

            // authentication (apiKey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetUpcomingTeachingEvents", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<TeachingEvent>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (List<TeachingEvent>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<TeachingEvent>)));
        }

        /// <summary>
        /// Searches for teaching events. Searches for teaching events by postcode. Optionally limit the results by distance (in miles) and the type of event.
        /// </summary>
        /// <exception cref="GetIntoTeachingApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="postcode"></param>
        /// <param name="radius"> (optional)</param>
        /// <param name="typeId"> (optional)</param>
        /// <param name="startAfter"> (optional)</param>
        /// <param name="startBefore"> (optional)</param>
        /// <param name="radiusInKm"> (optional)</param>
        /// <returns>List&lt;TeachingEvent&gt;</returns>
        public List<TeachingEvent> SearchTeachingEvents (string postcode, int? radius = null, int? typeId = null, DateTime? startAfter = null, DateTime? startBefore = null, double? radiusInKm = null)
        {
             ApiResponse<List<TeachingEvent>> localVarResponse = SearchTeachingEventsWithHttpInfo(postcode, radius, typeId, startAfter, startBefore, radiusInKm);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Searches for teaching events. Searches for teaching events by postcode. Optionally limit the results by distance (in miles) and the type of event.
        /// </summary>
        /// <exception cref="GetIntoTeachingApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="postcode"></param>
        /// <param name="radius"> (optional)</param>
        /// <param name="typeId"> (optional)</param>
        /// <param name="startAfter"> (optional)</param>
        /// <param name="startBefore"> (optional)</param>
        /// <param name="radiusInKm"> (optional)</param>
        /// <returns>ApiResponse of List&lt;TeachingEvent&gt;</returns>
        public ApiResponse< List<TeachingEvent> > SearchTeachingEventsWithHttpInfo (string postcode, int? radius = null, int? typeId = null, DateTime? startAfter = null, DateTime? startBefore = null, double? radiusInKm = null)
        {
            // verify the required parameter 'postcode' is set
            if (postcode == null)
                throw new ApiException(400, "Missing required parameter 'postcode' when calling TeachingEventsApi->SearchTeachingEvents");

            var localVarPath = "/api/teaching_events/search";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (postcode != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "Postcode", postcode)); // query parameter
            if (radius != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "Radius", radius)); // query parameter
            if (typeId != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "TypeId", typeId)); // query parameter
            if (startAfter != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "StartAfter", startAfter)); // query parameter
            if (startBefore != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "StartBefore", startBefore)); // query parameter
            if (radiusInKm != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "RadiusInKm", radiusInKm)); // query parameter

            // authentication (apiKey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("SearchTeachingEvents", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<TeachingEvent>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (List<TeachingEvent>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<TeachingEvent>)));
        }

        /// <summary>
        /// Searches for teaching events. Searches for teaching events by postcode. Optionally limit the results by distance (in miles) and the type of event.
        /// </summary>
        /// <exception cref="GetIntoTeachingApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="postcode"></param>
        /// <param name="radius"> (optional)</param>
        /// <param name="typeId"> (optional)</param>
        /// <param name="startAfter"> (optional)</param>
        /// <param name="startBefore"> (optional)</param>
        /// <param name="radiusInKm"> (optional)</param>
        /// <returns>Task of List&lt;TeachingEvent&gt;</returns>
        public async System.Threading.Tasks.Task<List<TeachingEvent>> SearchTeachingEventsAsync (string postcode, int? radius = null, int? typeId = null, DateTime? startAfter = null, DateTime? startBefore = null, double? radiusInKm = null)
        {
             ApiResponse<List<TeachingEvent>> localVarResponse = await SearchTeachingEventsAsyncWithHttpInfo(postcode, radius, typeId, startAfter, startBefore, radiusInKm);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Searches for teaching events. Searches for teaching events by postcode. Optionally limit the results by distance (in miles) and the type of event.
        /// </summary>
        /// <exception cref="GetIntoTeachingApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="postcode"></param>
        /// <param name="radius"> (optional)</param>
        /// <param name="typeId"> (optional)</param>
        /// <param name="startAfter"> (optional)</param>
        /// <param name="startBefore"> (optional)</param>
        /// <param name="radiusInKm"> (optional)</param>
        /// <returns>Task of ApiResponse (List&lt;TeachingEvent&gt;)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<List<TeachingEvent>>> SearchTeachingEventsAsyncWithHttpInfo (string postcode, int? radius = null, int? typeId = null, DateTime? startAfter = null, DateTime? startBefore = null, double? radiusInKm = null)
        {
            // verify the required parameter 'postcode' is set
            if (postcode == null)
                throw new ApiException(400, "Missing required parameter 'postcode' when calling TeachingEventsApi->SearchTeachingEvents");

            var localVarPath = "/api/teaching_events/search";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (postcode != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "Postcode", postcode)); // query parameter
            if (radius != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "Radius", radius)); // query parameter
            if (typeId != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "TypeId", typeId)); // query parameter
            if (startAfter != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "StartAfter", startAfter)); // query parameter
            if (startBefore != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "StartBefore", startBefore)); // query parameter
            if (radiusInKm != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "RadiusInKm", radiusInKm)); // query parameter

            // authentication (apiKey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("SearchTeachingEvents", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<TeachingEvent>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (List<TeachingEvent>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<TeachingEvent>)));
        }

    }
}
