/* 
 * Get into Teaching API - V1
 *
 *   Provides a RESTful API for integrating with the Get into Teaching CRM.    The Get into Teaching (GIT) API sits in front of the GIT CRM, which uses the [Microsoft Dynamics365](https://docs.microsoft.com/en-us/dynamics365/) platform (the [Customer Engagement](https://docs.microsoft.com/en-us/dynamics365/customerengagement/on-premises/developer/overview) module is used for storing Candidate information and the [Marketing](https://docs.microsoft.com/en-us/dynamics365/marketing/developer/using-events-api) module for managing Events).    The GIT API aims to provide:    * Simple, task-based RESTful APIs.  * Message queueing (while the GIT CRM is offline for updates).  * Validation to ensure consistency across services writing to the GIT CRM.                          
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GetIntoTeachingApi.Client.Api;
using GetIntoTeachingApi.Client.Model;
using GetIntoTeachingApi.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GetIntoTeachingApi.Client.Test
{
    /// <summary>
    ///  Class for testing Candidate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CandidateTests
    {
        // TODO uncomment below to declare an instance variable for Candidate
        //private Candidate instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Candidate
            //instance = new Candidate();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Candidate
        /// </summary>
        [Test]
        public void CandidateInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Candidate
            //Assert.IsInstanceOfType<Candidate> (instance, "variable 'instance' is a Candidate");
        }


        /// <summary>
        /// Test the property 'PreferredTeachingSubjectId'
        /// </summary>
        [Test]
        public void PreferredTeachingSubjectIdTest()
        {
            // TODO unit test for the property 'PreferredTeachingSubjectId'
        }
        /// <summary>
        /// Test the property 'PreferredEducationPhaseId'
        /// </summary>
        [Test]
        public void PreferredEducationPhaseIdTest()
        {
            // TODO unit test for the property 'PreferredEducationPhaseId'
        }
        /// <summary>
        /// Test the property 'LocationId'
        /// </summary>
        [Test]
        public void LocationIdTest()
        {
            // TODO unit test for the property 'LocationId'
        }
        /// <summary>
        /// Test the property 'InitialTeacherTrainingYearId'
        /// </summary>
        [Test]
        public void InitialTeacherTrainingYearIdTest()
        {
            // TODO unit test for the property 'InitialTeacherTrainingYearId'
        }
        /// <summary>
        /// Test the property 'ChannelId'
        /// </summary>
        [Test]
        public void ChannelIdTest()
        {
            // TODO unit test for the property 'ChannelId'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Test]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'FirstName'
        /// </summary>
        [Test]
        public void FirstNameTest()
        {
            // TODO unit test for the property 'FirstName'
        }
        /// <summary>
        /// Test the property 'LastName'
        /// </summary>
        [Test]
        public void LastNameTest()
        {
            // TODO unit test for the property 'LastName'
        }
        /// <summary>
        /// Test the property 'DateOfBirth'
        /// </summary>
        [Test]
        public void DateOfBirthTest()
        {
            // TODO unit test for the property 'DateOfBirth'
        }
        /// <summary>
        /// Test the property 'Telephone'
        /// </summary>
        [Test]
        public void TelephoneTest()
        {
            // TODO unit test for the property 'Telephone'
        }
        /// <summary>
        /// Test the property 'AddressLine1'
        /// </summary>
        [Test]
        public void AddressLine1Test()
        {
            // TODO unit test for the property 'AddressLine1'
        }
        /// <summary>
        /// Test the property 'AddressLine2'
        /// </summary>
        [Test]
        public void AddressLine2Test()
        {
            // TODO unit test for the property 'AddressLine2'
        }
        /// <summary>
        /// Test the property 'AddressLine3'
        /// </summary>
        [Test]
        public void AddressLine3Test()
        {
            // TODO unit test for the property 'AddressLine3'
        }
        /// <summary>
        /// Test the property 'AddressCity'
        /// </summary>
        [Test]
        public void AddressCityTest()
        {
            // TODO unit test for the property 'AddressCity'
        }
        /// <summary>
        /// Test the property 'AddressState'
        /// </summary>
        [Test]
        public void AddressStateTest()
        {
            // TODO unit test for the property 'AddressState'
        }
        /// <summary>
        /// Test the property 'AddressPostcode'
        /// </summary>
        [Test]
        public void AddressPostcodeTest()
        {
            // TODO unit test for the property 'AddressPostcode'
        }
        /// <summary>
        /// Test the property 'Qualifications'
        /// </summary>
        [Test]
        public void QualificationsTest()
        {
            // TODO unit test for the property 'Qualifications'
        }
        /// <summary>
        /// Test the property 'PastTeachingPositions'
        /// </summary>
        [Test]
        public void PastTeachingPositionsTest()
        {
            // TODO unit test for the property 'PastTeachingPositions'
        }
        /// <summary>
        /// Test the property 'PhoneCall'
        /// </summary>
        [Test]
        public void PhoneCallTest()
        {
            // TODO unit test for the property 'PhoneCall'
        }
        /// <summary>
        /// Test the property 'PrivacyPolicy'
        /// </summary>
        [Test]
        public void PrivacyPolicyTest()
        {
            // TODO unit test for the property 'PrivacyPolicy'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

    }

}
