/* 
 * Get into Teaching API - V1
 *
 *   Provides a RESTful API for integrating with the Get into Teaching CRM.    The Get into Teaching (GIT) API sits in front of the GIT CRM, which uses the [Microsoft Dynamics365](https://docs.microsoft.com/en-us/dynamics365/) platform (the [Customer Engagement](https://docs.microsoft.com/en-us/dynamics365/customerengagement/on-premises/developer/overview) module is used for storing Candidate information and the [Marketing](https://docs.microsoft.com/en-us/dynamics365/marketing/developer/using-events-api) module for managing Events).    The GIT API aims to provide:    * Simple, task-based RESTful APIs.  * Message queueing (while the GIT CRM is offline for updates).  * Validation to ensure consistency across services writing to the GIT CRM.                          
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GetIntoTeachingApi.Client.Api;
using GetIntoTeachingApi.Client.Model;
using GetIntoTeachingApi.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GetIntoTeachingApi.Client.Test
{
    /// <summary>
    ///  Class for testing HealthCheckResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class HealthCheckResponseTests
    {
        // TODO uncomment below to declare an instance variable for HealthCheckResponse
        //private HealthCheckResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of HealthCheckResponse
            //instance = new HealthCheckResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of HealthCheckResponse
        /// </summary>
        [Test]
        public void HealthCheckResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" HealthCheckResponse
            //Assert.IsInstanceOfType<HealthCheckResponse> (instance, "variable 'instance' is a HealthCheckResponse");
        }


        /// <summary>
        /// Test the property 'GitCommitSha'
        /// </summary>
        [Test]
        public void GitCommitShaTest()
        {
            // TODO unit test for the property 'GitCommitSha'
        }
        /// <summary>
        /// Test the property 'Environment'
        /// </summary>
        [Test]
        public void EnvironmentTest()
        {
            // TODO unit test for the property 'Environment'
        }
        /// <summary>
        /// Test the property 'Database'
        /// </summary>
        [Test]
        public void DatabaseTest()
        {
            // TODO unit test for the property 'Database'
        }
        /// <summary>
        /// Test the property 'Hangfire'
        /// </summary>
        [Test]
        public void HangfireTest()
        {
            // TODO unit test for the property 'Hangfire'
        }
        /// <summary>
        /// Test the property 'Crm'
        /// </summary>
        [Test]
        public void CrmTest()
        {
            // TODO unit test for the property 'Crm'
        }
        /// <summary>
        /// Test the property 'Notify'
        /// </summary>
        [Test]
        public void NotifyTest()
        {
            // TODO unit test for the property 'Notify'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

    }

}
