/* 
 * Get into Teaching API - V1
 *
 *   Provides a RESTful API for integrating with the Get into Teaching CRM.    The Get into Teaching (GIT) API sits in front of the GIT CRM, which uses the [Microsoft Dynamics365](https://docs.microsoft.com/en-us/dynamics365/) platform (the [Customer Engagement](https://docs.microsoft.com/en-us/dynamics365/customerengagement/on-premises/developer/overview) module is used for storing Candidate information and the [Marketing](https://docs.microsoft.com/en-us/dynamics365/marketing/developer/using-events-api) module for managing Events).    The GIT API aims to provide:    * Simple, task-based RESTful APIs.  * Message queueing (while the GIT CRM is offline for updates).  * Validation to ensure consistency across services writing to the GIT CRM.                          
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GetIntoTeachingApi.Client.Api;
using GetIntoTeachingApi.Client.Model;
using GetIntoTeachingApi.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GetIntoTeachingApi.Client.Test
{
    /// <summary>
    ///  Class for testing MappingInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MappingInfoTests
    {
        // TODO uncomment below to declare an instance variable for MappingInfo
        //private MappingInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MappingInfo
            //instance = new MappingInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MappingInfo
        /// </summary>
        [Test]
        public void MappingInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MappingInfo
            //Assert.IsInstanceOfType<MappingInfo> (instance, "variable 'instance' is a MappingInfo");
        }


        /// <summary>
        /// Test the property 'Class'
        /// </summary>
        [Test]
        public void ClassTest()
        {
            // TODO unit test for the property 'Class'
        }
        /// <summary>
        /// Test the property 'LogicalName'
        /// </summary>
        [Test]
        public void LogicalNameTest()
        {
            // TODO unit test for the property 'LogicalName'
        }
        /// <summary>
        /// Test the property 'Fields'
        /// </summary>
        [Test]
        public void FieldsTest()
        {
            // TODO unit test for the property 'Fields'
        }
        /// <summary>
        /// Test the property 'Relationships'
        /// </summary>
        [Test]
        public void RelationshipsTest()
        {
            // TODO unit test for the property 'Relationships'
        }

    }

}
